baseURL = "https://chriskujawa.github.io/sportsclub/"
languageCode = "de"
defaultContentLanguage = "de"
title = "Sport Dojo Berlin"
theme = "ananke"

[params]
  description = "Judo ab 3 Jahren — Sport Dojo Berlin e.V."
  background_color_class = "bg-near-black"
  show_reading_time = false
  site_logo = "images/logo.jpg"
  contact_email = "sport-dojo-berlin@outlook.de"

[menu]
  [[menu.main]]
    identifier = "aktuelles"
    name = "Aktuelles"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "angebot"
    name = "Angebot"
    url = "/angebot/"
    weight = 2
  [[menu.main]]
    identifier = "ueber-uns"
    name = "Über uns"
    url = "/ueber-uns/"
    weight = 3
  [[menu.main]]
    identifier = "impressum"
    name = "Impressum"
    url = "/impressum/"
    weight = 4
